GCC = arm-none-eabi-gcc
AR = arm-none-eabi-ar
OBJCOPY = arm-none-eabi-objcopy

OBJS = obj_gam-sdk/rimeaddr.o
OBJS += obj_gam-sdk/rime.o
OBJS += obj_gam-sdk/timesynch.o
OBJS += obj_gam-sdk/rimestats.o
OBJS += obj_gam-sdk/announcement.o
OBJS += obj_gam-sdk/polite-announcement.o
OBJS += obj_gam-sdk/broadcast-announcement.o
OBJS += obj_gam-sdk/broadcast.o
OBJS += obj_gam-sdk/stbroadcast.o
OBJS += obj_gam-sdk/unicast.o
OBJS += obj_gam-sdk/stunicast.o
OBJS += obj_gam-sdk/runicast.o
OBJS += obj_gam-sdk/abc.o
OBJS += obj_gam-sdk/rucb.o
OBJS += obj_gam-sdk/polite.o
OBJS += obj_gam-sdk/ipolite.o
OBJS += obj_gam-sdk/netflood.o
OBJS += obj_gam-sdk/multihop.o
OBJS += obj_gam-sdk/rmh.o
OBJS += obj_gam-sdk/trickle.o
OBJS += obj_gam-sdk/mesh.o
OBJS += obj_gam-sdk/route.o
OBJS += obj_gam-sdk/route-discovery.o
OBJS += obj_gam-sdk/collect.o
OBJS += obj_gam-sdk/collect-neighbor.o
OBJS += obj_gam-sdk/neighbor-discovery.o
OBJS += obj_gam-sdk/collect-link-estimate.o
OBJS += obj_gam-sdk/rudolph0.o
OBJS += obj_gam-sdk/rudolph1.o
OBJS += obj_gam-sdk/rudolph2.o
OBJS += obj_gam-sdk/chameleon.o
OBJS += obj_gam-sdk/channel.o
OBJS += obj_gam-sdk/chameleon-raw.o
OBJS += obj_gam-sdk/chameleon-bitopt.o
#OBJS += obj_gam-sdk/cxmac.o
#OBJS += obj_gam-sdk/xmac.o
OBJS += obj_gam-sdk/nullmac.o
#OBJS += obj_gam-sdk/lpp.o
OBJS += obj_gam-sdk/frame802154.o
#OBJS += obj_gam-sdk/sicslowmac.o
OBJS += obj_gam-sdk/nullrdc.o
#OBJS += obj_gam-sdk/nullrdc-noframer.o
OBJS += obj_gam-sdk/mac.o
#OBJS += obj_gam-sdk/framer-nullmac.o
OBJS += obj_gam-sdk/framer-802154.o
#OBJS += obj_gam-sdk/csma.o
#OBJS += obj_gam-sdk/contikimac.o
#OBJS += obj_gam-sdk/phase.o
OBJS += obj_gam-sdk/process.o
OBJS += obj_gam-sdk/procinit.o
OBJS += obj_gam-sdk/autostart.o
OBJS += obj_gam-sdk/elfloader.o
OBJS += obj_gam-sdk/profile.o
OBJS += obj_gam-sdk/timetable.o
OBJS += obj_gam-sdk/timetable-aggregate.o
#OBJS += obj_gam-sdk/compower.o
OBJS += obj_gam-sdk/serial-line.o
OBJS += obj_gam-sdk/cfs-coffee.o
OBJS += obj_gam-sdk/memb.o
OBJS += obj_gam-sdk/mmem.o
OBJS += obj_gam-sdk/timer.o
OBJS += obj_gam-sdk/list.o
OBJS += obj_gam-sdk/etimer.o
OBJS += obj_gam-sdk/ctimer.o
#OBJS += obj_gam-sdk/energest.o
OBJS += obj_gam-sdk/rtimer.o
OBJS += obj_gam-sdk/stimer.o
#OBJS += obj_gam-sdk/print-stats.o
#OBJS += obj_gam-sdk/ifft.o
#OBJS += obj_gam-sdk/crc16.o
OBJS += obj_gam-sdk/random.o
#OBJS += obj_gam-sdk/checkpoint.o
OBJS += obj_gam-sdk/ringbuf.o
OBJS += obj_gam-sdk/netstack.o
OBJS += obj_gam-sdk/uip-debug.o
OBJS += obj_gam-sdk/packetbuf.o
OBJS += obj_gam-sdk/queuebuf.o
OBJS += obj_gam-sdk/packetqueue.o
#OBJS += obj_gam-sdk/uip.o
#OBJS += obj_gam-sdk/uiplib.o
#OBJS += obj_gam-sdk/resolv.o
#OBJS += obj_gam-sdk/tcpip.o
#OBJS += obj_gam-sdk/psock.o
#OBJS += obj_gam-sdk/hc.o
#OBJS += obj_gam-sdk/uip-split.o
#OBJS += obj_gam-sdk/uip-fw.o
#OBJS += obj_gam-sdk/uip-fw-drv.o
#OBJS += obj_gam-sdk/uip_arp.o
#OBJS += obj_gam-sdk/tcpdump.o
#OBJS += obj_gam-sdk/uip-neighbor.o
#OBJS += obj_gam-sdk/uip-udp-packet.o
#OBJS += obj_gam-sdk/uip-over-mesh.o
#OBJS += obj_gam-sdk/dhcpc.o
#OBJS += obj_gam-sdk/uaodv.o
#OBJS += obj_gam-sdk/uaodv-rt.o
#OBJS += obj_gam-sdk/nullradio.o
OBJS += obj_gam-sdk/contiki-mc1322x-main.o
OBJS += obj_gam-sdk/clock.o
OBJS += obj_gam-sdk/slip.o
OBJS += obj_gam-sdk/xmem.o
OBJS += obj_gam-sdk/debug-uart.o
OBJS += obj_gam-sdk/rtimer-arch.o
OBJS += obj_gam-sdk/watchdog.o
OBJS += obj_gam-sdk/contiki-crm.o
OBJS += obj_gam-sdk/contiki-maca.o
OBJS += obj_gam-sdk/contiki-misc.o
OBJS += obj_gam-sdk/leds-arch.o
OBJS += obj_gam-sdk/leds.o
OBJS += obj_gam-sdk/contiki-uart.o
#OBJS += obj_gam-sdk/slip-uart1.o
OBJS += obj_gam-sdk/dbg-printf.o
OBJS += obj_gam-sdk/dbg-snprintf.o
OBJS += obj_gam-sdk/dbg-sprintf.o
OBJS += obj_gam-sdk/strformat.o
#OBJS += obj_gam-sdk/adc.o
OBJS += obj_gam-sdk/Delay.o
OBJS += obj_gam-sdk/gpio.o
OBJS += obj_gam-sdk/gpio-util.o
OBJS += obj_gam-sdk/maca.o
OBJS += obj_gam-sdk/nvm.o
OBJS += obj_gam-sdk/printf.o
#OBJS += obj_gam-sdk/pwm.o
OBJS += obj_gam-sdk/rtc.o
OBJS += obj_gam-sdk/tmr.o
OBJS += obj_gam-sdk/uart1.o
OBJS += obj_gam-sdk/default_lowlevel.o
OBJS += obj_gam-sdk/isr.o
OBJS += obj_gam-sdk/start.o

INCLUDES = -I../../../cpu/mc1322x -I../../../cpu/mc1322x/loader\
	 -I../../../cpu/mc1322x/dbg-io -I../../../platform/gam-sdk\
	 -I../../../cpu/mc1322x/lib/include -I../../../cpu/mc1322x/src\
	 -I. -I../../../core -I../../../cpu/mc1322x/board\
	 -I../../../platform/gam-sdk/. -I../../../platform/gam-sdk/dev\
	 -I../../../platform/gam-sdk/apps -I../../../platform/gam-sdk/net\
	 -I../../../cpu/mc1322x/. -I../../../cpu/mc1322x/lib\
	 -I../../../cpu/mc1322x/src -I../../../cpu/mc1322x/board\
	 -I../../../cpu/mc1322x/dev -I../../../cpu/mc1322x/../arm/common/dbg-io\
	 -I../../../core/dev -I../../../core/lib -I../../../core/net\
	 -I../../../core/net/mac -I../../../core/net/rime\
	 -I../../../core/net/rpl -I../../../core/sys -I../../../core/cfs\
	 -I../../../core/ctk -I../../../core/lib/ctk -I../../../core/loader\
	 -I../../../core/. -Iobj_gam-sdk -I../../../cpu/mc1322x/board

CFLAGS = -DCONTIKI_NO_NET -DCONTIKI=1 -DCONTIKI_TARGET_GAM_SDK=1   -DWITH_ASCII -DMCK= -Werror\
	 -mcpu=arm7tdmi-s -mthumb-interwork -march=armv4t -mtune=arm7tdmi-s\
	 -DCONFIG_ARM -D__ARM__  -Os -DRUN_AS_SYSTEM -DROM_RUN\
	 -fno-strict-aliasing  -fno-common -ffixed-r8 -msoft-float\
	 -fno-builtin-printf -fno-builtin-sprintf\
	 -DBOARD=gam-sdk -DAUTOSTART_ENABLE -mthumb\
	 -mcallee-super-interworking 

all: lib firm bin

lib: $(OBJS)
	$(AR) rcf contiki-gam-sdk.a $(OBJS)

firm: test-coffee.c
	$(GCC) $(CFLAGS) $(INCLUDES) test-coffee.c -c -o test-coffee.co
	$(GCC) -mthumb -mcallee-super-interworking -I../../../core/loader -c symbols.c -o obj_gam-sdk/symbols.o
	$(GCC) -T ../../../cpu/mc1322x/mc1322x.lds $(CFLAGS) $(INCLUDES)\
		-o test-coffee.elf obj_gam-sdk/board.h test-coffee.co\
		obj_gam-sdk/contiki-mc1322x-main.o obj_gam-sdk/start.o\
		obj_gam-sdk/symbols.o contiki-gam-sdk.a

bin: test-coffee.elf
	$(OBJCOPY) -O binary test-coffee.elf test-coffee_gam-sdk.bin

clean:
	rm *.co *.elf *.bin
